### PR TITLE
Added angular support.

### PR DESCRIPTION
**Pull request by dawnerd**
Hows this?

### CODE REVIEW

**Comment by dawnerd** [comment]
Derp, forgot the example directory.

**Comment by jgallen23** [comment]
looks great. can you give it a shot with angular-notice and make sure everything is working correctly?

**Comment by dawnerd** [comment]
Looks like it worked fine, except it named the output file to angular.angular-notice. Not really a problem with ft-init though.

**Comment by jgallen23** [comment]
did you just need to change the name prop in the Gruntfile to notice?

**Comment by dawnerd** [comment]
Yep, that did the trick.

**Comment by jgallen23** [comment]
released as 0.2.0

**Pull request merged**
